# Generated by Django 4.1 on 2022-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_event_alter_outer_out_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=10)),
                ('csvFile', models.FileField(upload_to='uploads/', verbose_name='첨부 파일')),
            ],
        ),
    ]
