# Generated by Django 4.1 on 2022-09-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='csvFile',
            new_name='file',
        ),
    ]
