# Generated by Django 4.1 on 2022-09-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_csvfile_people_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='file',
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
