# Generated by Django 4.1 on 2022-09-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_people_file_people_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.event'),
        ),
    ]
