# Generated by Django 4.1 on 2022-09-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_outer_school_alter_people_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='outer',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.event'),
        ),
    ]
