# Generated by Django 4.1 on 2022-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_outer_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
