# Generated by Django 4.1 on 2022-09-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_find'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outer',
            name='event',
        ),
        migrations.RemoveField(
            model_name='outer',
            name='school',
        ),
        migrations.CreateModel(
            name='Outer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=5)),
                ('school', models.CharField(max_length=10, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.event')),
            ],
        ),
    ]
