# Generated by Django 4.1 on 2022-09-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_remove_outer_event_remove_outer_school_outer2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outer2',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='outer2',
            name='out_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
